definitions:
  model.Menu:
    properties:
      id:
        type: integer
      image:
        type: string
      ingredients:
        items:
          type: string
        type: array
      name:
        type: string
      price:
        type: number
      type:
        type: string
    type: object
  model.WorkingHours:
    properties:
      closing:
        type: string
      opening:
        type: string
    type: object
  response.Error:
    properties:
      error:
        type: string
    type: object
  response.MenuResponse:
    properties:
      menu:
        items:
          $ref: '#/definitions/model.Menu'
        type: array
    type: object
  response.SupplierCollectionResponse:
    properties:
      restaurants:
        items:
          $ref: '#/definitions/response.SupplierResponse'
        type: array
    type: object
  response.SupplierResponse:
    properties:
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      type:
        type: string
      workingHours:
        $ref: '#/definitions/model.WorkingHours'
    type: object
info:
  contact: {}
paths:
  /suppliers:
    get:
      description: Get suppliers
      operationId: get-suppliers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SupplierCollectionResponse'
      summary: Get suppliers
      tags:
      - Suppliers Actions
  /suppliers/{id}/menu:
    get:
      description: Get menu by supplier id
      operationId: get-supplier-menu
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MenuResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get supplier menu by supplier id
      tags:
      - Supplier Actions
  /suppliers/{id}/menu/{position_id}:
    get:
      description: Get menu position by supplier id and position id
      operationId: get-supplier-menu-position
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      - description: Supplier menu position ID
        in: path
        name: position_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get supplier menu by supplier id and position id
      tags:
      - Supplier Actions
swagger: "2.0"
